---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-eksctl
  region: us-east-1
  version: "1.21"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-east-1:914339014973:key/998739dc-6d7f-4afe-b2ab-c4154a125fa5
